# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 535)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 341, 161))
        self.groupBox.setObjectName("groupBox")
        self.pb_load_folder = QtWidgets.QPushButton(self.groupBox)
        self.pb_load_folder.setGeometry(QtCore.QRect(10, 20, 321, 41))
        self.pb_load_folder.setObjectName("pb_load_folder")
        self.pb_pre_image = QtWidgets.QPushButton(self.groupBox)
        self.pb_pre_image.setGeometry(QtCore.QRect(10, 70, 151, 41))
        self.pb_pre_image.setObjectName("pb_pre_image")
        self.pb_next_image = QtWidgets.QPushButton(self.groupBox)
        self.pb_next_image.setGeometry(QtCore.QRect(180, 70, 151, 41))
        self.pb_next_image.setObjectName("pb_next_image")
        self.label_cuurrent_image = QtWidgets.QLabel(self.groupBox)
        self.label_cuurrent_image.setGeometry(QtCore.QRect(20, 120, 301, 31))
        self.label_cuurrent_image.setObjectName("label_cuurrent_image")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 180, 341, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pb_detection = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_detection.setGeometry(QtCore.QRect(10, 20, 321, 41))
        self.pb_detection.setObjectName("pb_detection")
        self.label_iou = QtWidgets.QLabel(self.groupBox_2)
        self.label_iou.setGeometry(QtCore.QRect(20, 80, 301, 16))
        self.label_iou.setObjectName("label_iou")
        self.label_accuracy = QtWidgets.QLabel(self.groupBox_2)
        self.label_accuracy.setGeometry(QtCore.QRect(20, 110, 301, 16))
        self.label_accuracy.setObjectName("label_accuracy")
        self.label_precision = QtWidgets.QLabel(self.groupBox_2)
        self.label_precision.setGeometry(QtCore.QRect(20, 140, 301, 16))
        self.label_precision.setObjectName("label_precision")
        self.label_recall = QtWidgets.QLabel(self.groupBox_2)
        self.label_recall.setGeometry(QtCore.QRect(20, 170, 301, 16))
        self.label_recall.setObjectName("label_recall")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 400, 341, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pb_segmentation = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_segmentation.setGeometry(QtCore.QRect(10, 20, 321, 41))
        self.pb_segmentation.setObjectName("pb_segmentation")
        self.label_dice_coefficient = QtWidgets.QLabel(self.groupBox_3)
        self.label_dice_coefficient.setGeometry(QtCore.QRect(20, 80, 301, 16))
        self.label_dice_coefficient.setObjectName("label_dice_coefficient")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Image"))
        self.pb_load_folder.setText(_translate("MainWindow", "Load Folder"))
        self.pb_pre_image.setText(_translate("MainWindow", "Pre"))
        self.pb_next_image.setText(_translate("MainWindow", "Next"))
        self.label_cuurrent_image.setText(_translate("MainWindow", "Current Image : "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Detection"))
        self.pb_detection.setText(_translate("MainWindow", "Detection"))
        self.label_iou.setText(_translate("MainWindow", "IoU : "))
        self.label_accuracy.setText(_translate("MainWindow", "Accuracy : "))
        self.label_precision.setText(_translate("MainWindow", "Precision :"))
        self.label_recall.setText(_translate("MainWindow", "Recall : "))
        self.groupBox_3.setTitle(_translate("MainWindow", "Segment"))
        self.pb_segmentation.setText(_translate("MainWindow", "Segmentation"))
        self.label_dice_coefficient.setText(_translate("MainWindow", "Dice Coefficient : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
